# (a)

In [1]:
import numpy as np
rng = np.random.default_rng(0)

In [2]:
n = 100
X = rng.normal(size=n)
eps = rng.normal(loc = 0.25, scale = 0.5, size=n)
print(X)
print(eps)

[ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505
  1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446  0.04132598
 -2.32503077 -0.21879166 -1.24591095 -0.73226735 -0.54425898 -0.31630016
  0.41163054  1.04251337 -0.12853466  1.36646347 -0.66519467  0.35151007
  0.90347018  0.0940123  -0.74349925 -0.92172538 -0.45772583  0.22019512
 -1.00961818 -0.20917557 -0.15922501  0.54084558  0.21465912  0.35537271
 -0.65382861 -0.12961363  0.78397547  1.49343115 -1.25906553  1.51392377
  1.34587542  0.7813114   0.26445563 -0.31392281  1.45802068  1.96025832
  1.80163487  1.31510376  0.35738041 -1.20831863 -0.00445413  0.65647494
 -1.28836146  0.39512206  0.42986369  0.69604272 -1.18411797 -0.66170257
 -0.43643525 -1.16980191  1.73936788 -0.49591073  0.32896963 -0.25857255
  1.58347288  1.32036099  0.63335262 -2.20350988  0.05202897  0.68368619
  1.00396158 -0.61790704  1.82201136 -1.32043097 -0.66152802  0.93504999
  0.04905461  2.00239258  0.18851919 -0.63319409 -0

# (b)

In [3]:
beta0 = 0.325
beta1 = -3
beta2 = 1.5
beta3 = 0.75

Y = beta0 + beta1*X + beta2*np.square(X)+beta3*np.power(X, 3) + eps
Y

array([ 4.74353560e-01,  1.49061956e+00, -6.16205719e-01, -2.59510985e-01,
        2.93366231e+00, -9.18396480e-01,  5.20097014e-01,  2.68315387e-02,
        2.04260993e+00,  5.44665498e+00,  2.55511649e+00,  5.08276599e-01,
        6.19446082e+00,  1.39638174e+00,  5.53774479e+00,  2.90245059e+00,
        3.24168030e+00,  2.01328267e+00,  6.84441852e-02,  5.09922400e-01,
        1.37758718e+00,  1.61210097e+00,  3.05135328e+00, -9.75003880e-01,
       -4.25446718e-01, -7.79135627e-02,  2.61506372e+00,  4.15646106e+00,
        1.90624754e+00, -5.19751483e-01,  3.83949760e+00,  1.39550263e+00,
        1.26701233e+00,  1.71116558e-01,  6.01490573e-04,  2.52896347e-01,
        3.66922622e+00,  1.56249016e+00, -1.67626825e+00,  2.55269389e+00,
        5.40292916e+00,  2.28545760e+00,  1.26847795e+00, -3.04172168e-01,
        6.01167713e-02,  1.46193085e+00,  7.63478635e-01,  6.05307177e+00,
        4.02299080e+00,  1.46986919e+00, -4.15709675e-01,  5.10860481e+00,
        1.63589114e-01, -

# (c)

In [4]:
def nCp(sigma2, estimator, X, Y):
    "Negative Cp statistic"
    n, p = X.shape
    Yhat = estimator.predict(X)
    RSS = np.sum((Y - Yhat)**2)
    return -(RSS + 2 * p *sigma2) / n

In [5]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=10, include_bias=False)
X_poly_array = poly.fit_transform(X.reshape(-1, 1))
X_poly_array

array([[ 1.25730221e-01,  1.58080885e-02,  1.98755446e-03,
         2.49895662e-04,  3.14194368e-05,  3.95037274e-06,
         4.96681238e-07,  6.24478418e-08,  7.85158096e-09,
         9.87181010e-10],
       [-1.32104863e-01,  1.74516949e-02, -2.30545377e-03,
         3.04561655e-04, -4.02340758e-05,  5.31511708e-06,
        -7.02152816e-07,  9.27578017e-08, -1.22537567e-08,
         1.61878086e-09],
       [ 6.40422650e-01,  4.10141171e-01,  2.62663696e-01,
         1.68215780e-01,  1.07729196e-01,  6.89922172e-02,
         4.41841786e-02,  2.82965487e-02,  1.81217507e-02,
         1.16055796e-02],
       [ 1.04900117e-01,  1.10040346e-02,  1.15432452e-03,
         1.21088777e-04,  1.27022269e-05,  1.33246509e-06,
         1.39775744e-07,  1.46624919e-08,  1.53809712e-09,
         1.61346568e-10],
       [-5.35669373e-01,  2.86941677e-01, -1.53705868e-01,
         8.23355262e-02, -4.41046197e-02,  2.36254940e-02,
        -1.26554536e-02,  6.77913887e-03, -3.63137707e-03,
         1.

In [6]:
import pandas as pd
column_names = [f'X^{i}' for i in range(1, 11)]
X_poly_df = pd.DataFrame(X_poly_array, columns=column_names)

In [7]:
from ISLP.models import ModelSpec as MS
design = MS(X_poly_df.columns)
X_design = design.fit_transform(X_poly_df)
X_design

,intercept,X^1,X^2,X^3,X^4,X^5,X^6,X^7,X^8,X^9,X^10
0,1.0,0.125730,0.015808,0.001988,0.000250,0.000031,0.000004,4.966812e-07,6.244784e-08,7.851581e-09,9.871810e-10
1,1.0,-0.132105,0.017452,-0.002305,0.000305,-0.000040,0.000005,-7.021528e-07,9.275780e-08,-1.225376e-08,1.618781e-09
2,1.0,0.640423,0.410141,0.262664,0.168216,0.107729,0.068992,4.418418e-02,2.829655e-02,1.812175e-02,1.160558e-02
3,1.0,0.104900,0.011004,0.001154,0.000121,0.000013,0.000001,1.397757e-07,1.466249e-08,1.538097e-09,1.613466e-10
4,1.0,-0.535669,0.286942,-0.153706,0.082336,-0.044105,0.023625,-1.265545e-02,6.779139e-03,-3.631377e-03,1.945217e-03
...,...,...,...,...,...,...,...,...,...,...,...
95,1.0,1.031453,1.063895,1.097358,1.131874,1.167474,1.204195,1.242071e+00,1.281138e+00,1.321433e+00,1.362997e+00
96,1.0,0.161010,0.025924,0.004174,0.000672,0.000108,0.000017,2.805188e-06,4.516621e-07,7.272193e-08,1.170893e-08
97,1.0,-0.585529,0.342844,-0.200745,0.117542,-0.068824,0.040299,-2.359598e-02,1.381612e-02,-8.089739e-03,4.736775e-03
98,1.0,-1.341220,1.798870,-2.412680,3.235934,-4.340099,5.821026,-7.807275e+00,1.047127e+01,-1.404428e+01,1.883646e+01


In [8]:
from statsmodels.api import OLS
sigma2 = OLS(Y, X_design).fit().scale
sigma2

np.float64(0.229489232608776)

In [9]:
from functools import partial
neg_Cp = partial(nCp, sigma2)

In [10]:
from ISLP.models import Stepwise, sklearn_selected
Strategy = Stepwise.fixed_steps(design, n_steps = 10, direction='forward')

In [11]:
from statsmodels.api import OLS
selector = sklearn_selected(OLS, Strategy, scoring=neg_Cp)
selector.fit(X_poly_df, Y)

In [12]:
selector.selected_state_

(Feature(variables=('X^1',), name='X^1', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^10',), name='X^10', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^2',), name='X^2', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^3',), name='X^3', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^4',), name='X^4', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^5',), name='X^5', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^6',), name='X^6', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^7',), name='X^7', encoder=None, use_transform=True, pure_columns=True, override

In [13]:
for state, result in selector.selector_.results_.items():
    print(f"Model Size: {len(state)} -> Negative Cp: {result:.4f}")

Model Size: 0 -> Negative Cp: -4.3868
Model Size: 1 -> Negative Cp: -3.4607
Model Size: 1 -> Negative Cp: -2.5591
Model Size: 1 -> Negative Cp: -4.2169
Model Size: 1 -> Negative Cp: -2.9833
Model Size: 1 -> Negative Cp: -4.3095
Model Size: 1 -> Negative Cp: -3.3415
Model Size: 1 -> Negative Cp: -4.2895
Model Size: 1 -> Negative Cp: -3.5667
Model Size: 1 -> Negative Cp: -4.2433
Model Size: 1 -> Negative Cp: -3.7127
Model Size: 2 -> Negative Cp: -1.1423
Model Size: 2 -> Negative Cp: -2.3115
Model Size: 2 -> Negative Cp: -2.5380
Model Size: 2 -> Negative Cp: -2.5420
Model Size: 2 -> Negative Cp: -2.5480
Model Size: 2 -> Negative Cp: -2.5637
Model Size: 2 -> Negative Cp: -2.5523
Model Size: 2 -> Negative Cp: -2.5594
Model Size: 2 -> Negative Cp: -2.5538
Model Size: 3 -> Negative Cp: -0.2402
Model Size: 3 -> Negative Cp: -0.9333
Model Size: 3 -> Negative Cp: -0.2736
Model Size: 3 -> Negative Cp: -0.8356
Model Size: 3 -> Negative Cp: -0.3196
Model Size: 3 -> Negative Cp: -0.7498
Model Size: 

In [14]:
for state, result in selector.selector_.results_.items():
    if len(state) == 3:
        feature_names = [f.name for f in state]
        print(f"Model Size 3 Features: {feature_names} -> Negative Cp: {result:.4f}")

Model Size 3 Features: ['X^1', 'X^2', 'X^3'] -> Negative Cp: -0.2402
Model Size 3 Features: ['X^1', 'X^2', 'X^4'] -> Negative Cp: -0.9333
Model Size 3 Features: ['X^1', 'X^2', 'X^5'] -> Negative Cp: -0.2736
Model Size 3 Features: ['X^1', 'X^2', 'X^6'] -> Negative Cp: -0.8356
Model Size 3 Features: ['X^1', 'X^2', 'X^7'] -> Negative Cp: -0.3196
Model Size 3 Features: ['X^1', 'X^2', 'X^8'] -> Negative Cp: -0.7498
Model Size 3 Features: ['X^1', 'X^2', 'X^9'] -> Negative Cp: -0.3607
Model Size 3 Features: ['X^1', 'X^10', 'X^2'] -> Negative Cp: -0.6858


# (d)

# (e)

In [15]:
from sklearn.linear_model import LassoCV
lambdas = np.logspace(-4, 4, num=100)
lambdas

array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-03, 5.99484250e-03, 7.22080902e-03,
       8.69749003e-03, 1.04761575e-02, 1.26185688e-02, 1.51991108e-02,
       1.83073828e-02, 2.20513074e-02, 2.65608778e-02, 3.19926714e-02,
       3.85352859e-02, 4.64158883e-02, 5.59081018e-02, 6.73415066e-02,
       8.11130831e-02, 9.77009957e-02, 1.17681195e-01, 1.41747416e-01,
       1.70735265e-01, 2.05651231e-01, 2.47707636e-01, 2.98364724e-01,
       3.59381366e-01, 4.32876128e-01, 5.21400829e-01, 6.28029144e-01,
       7.56463328e-01, 9.11162756e-01, 1.09749877e+00, 1.32194115e+00,
       1.59228279e+00, 1.91791026e+00, 2.31012970e+00, 2.78255940e+00,
      

In [16]:
lasso = LassoCV(alphas=lambdas, max_iter=1000000)
lasso.fit(X_poly_df, Y)

/home/sonu/miniconda3/envs/islp/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.0603840985887345, tolerance: 0.03556078578705881
  model = cd_fast.enet_coordinate_descent_gram(
/home/sonu/miniconda3/envs/islp/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.08290434826937698, tolerance: 0.03556078578705881
  model = cd_fast.enet_coordinate_descent_gram(
/home/sonu/miniconda3/envs/islp/lib/python3.13/site-packages/sklearn/linear_model/_coordinate_descent.py:681: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.08426044907619357, tolerance: 0.03556078578705881
  model = cd_fast.enet_coordinate_descent_gram(
/home/sonu/miniconda3/envs/is

LassoCV(alphas=array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-0...
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04]),
        max_iter=1000000)

In [17]:
lasso.alpha_

np.float64(0.005994842503189409)

In [18]:
## The warning is there because multiple variables are on different we need to scale the variable
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_poly_df)
X_poly_df_scaled = scaler.transform(X_poly_df)
X_poly_df_scaled

array([[ 4.63903071e-02, -8.21497443e-01, -9.39651169e-02,
        -4.59070916e-01, -3.86632710e-02, -3.12734048e-01,
         1.68008537e-02, -2.41288019e-01,  5.63634258e-02,
        -2.02158563e-01],
       [-2.21593189e-01, -8.20024151e-01, -9.56301009e-02,
        -4.59059042e-01, -3.86701094e-02, -3.12733984e-01,
         1.68008294e-02, -2.41288019e-01,  5.63634257e-02,
        -2.02158563e-01],
       [ 5.81341075e-01, -4.68026104e-01,  7.13452304e-03,
        -4.22586321e-01, -2.83848957e-02, -3.09517671e-01,
         1.76984506e-02, -2.41021962e-01,  5.64373476e-02,
        -2.02137225e-01],
       [ 2.47403285e-02, -8.25803689e-01, -9.42882737e-02,
        -4.59098895e-01, -3.86650573e-02, -3.12734170e-01,
         1.68008465e-02, -2.41288019e-01,  5.63634258e-02,
        -2.02158563e-01],
       [-6.41042033e-01, -5.78459369e-01, -1.54348660e-01,
        -4.41240742e-01, -4.28754914e-02, -3.11632762e-01,
         1.65437466e-02, -2.41224279e-01,  5.63486127e-02,
        -2.

In [19]:
lasso_scaled = LassoCV(alphas=lambdas, max_iter=100000, tol=0.001)
lasso_scaled.fit(X_poly_df_scaled, Y)
lasso_scaled.alpha_

np.float64(0.002848035868435802)

In [20]:
import pandas as pd
pd.Series(lasso_scaled.coef_, index=X_poly_df.columns)

X^1    -2.599186
X^2     1.721081
X^3     1.502134
X^4     0.005180
X^5     0.000000
X^6     0.000000
X^7     0.070982
X^8     0.000000
X^9     0.128528
X^10    0.000000
dtype: float64

# (f)

In [21]:
beta7 = 2.3
Y_new = beta0 + beta7*X**7 + eps

In [22]:
lasso_f = LassoCV(alphas=lambdas, max_iter=100000, tol=0.001)
lasso_f.fit(X_poly_df_scaled, Y_new)

LassoCV(alphas=array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-0...
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04]),
        max_iter=100000, tol=0.001)

In [24]:
pd.Series(lasso_f.coef_, index=X_poly_df.columns)

X^1      2.968933
X^2      2.401563
X^3    -20.610220
X^4     -3.895683
X^5     59.839580
X^6     -4.273573
X^7     41.617251
X^8      3.223295
X^9     31.007571
X^10     3.852450
dtype: float64

In [25]:
Strategy_y = Stepwise.fixed_steps(design, n_steps = 10, direction='forward')
selector_y = sklearn_selected(OLS, Strategy_y, scoring=neg_Cp)
selector_y.fit(X_poly_df, Y_new)
selector_y.selected_state_

(Feature(variables=('X^1',), name='X^1', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^10',), name='X^10', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^2',), name='X^2', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^3',), name='X^3', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^4',), name='X^4', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^5',), name='X^5', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^6',), name='X^6', encoder=None, use_transform=True, pure_columns=True, override_encoder_colnames=False),
 Feature(variables=('X^7',), name='X^7', encoder=None, use_transform=True, pure_columns=True, override

In [27]:
for state, result in selector_y.selector_.results_.items():
    print(f"Model Size: {len(state)} -> Negative Cp: {result:.4f}")

Model Size: 0 -> Negative Cp: -12810.9008
Model Size: 1 -> Negative Cp: -9024.5873
Model Size: 1 -> Negative Cp: -12088.2224
Model Size: 1 -> Negative Cp: -3159.0735
Model Size: 1 -> Negative Cp: -10247.2726
Model Size: 1 -> Negative Cp: -511.1526
Model Size: 1 -> Negative Cp: -8149.9720
Model Size: 1 -> Negative Cp: -0.2365
Model Size: 1 -> Negative Cp: -6427.2936
Model Size: 1 -> Negative Cp: -229.3883
Model Size: 1 -> Negative Cp: -5194.8341
Model Size: 2 -> Negative Cp: -0.2384
Model Size: 2 -> Negative Cp: -0.2410
Model Size: 2 -> Negative Cp: -0.2407
Model Size: 2 -> Negative Cp: -0.2411
Model Size: 2 -> Negative Cp: -0.2411
Model Size: 2 -> Negative Cp: -0.2411
Model Size: 2 -> Negative Cp: -0.2410
Model Size: 2 -> Negative Cp: -0.2406
Model Size: 2 -> Negative Cp: -0.2410
Model Size: 3 -> Negative Cp: -0.2428
Model Size: 3 -> Negative Cp: -0.2390
Model Size: 3 -> Negative Cp: -0.2425
Model Size: 3 -> Negative Cp: -0.2378
Model Size: 3 -> Negative Cp: -0.2422
Model Size: 3 -> Ne